version: '3.8'
services:
 api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - path: .env
    volumes:
      - .:/api
      - /api/node_modules
